name: PR Agent
on:
  issue_comment:
    types: [created]

jobs:
  review:
    if: contains(github.event.comment.body, '@agent')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leegmoore/pr-agent-action@main
        with:
          model: "claude-sonnet-4-20250514"
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
